### ISSUE TITLE
V. 1.5.0 crashes in start.

### ISSUE THREAD

**Issue by K-Ivy** [Keksuccino/SpiffyHUD#11]
With nothing extra, just the required depens, this errors start and crashes the game. I don't know enough to say anything else.

```
[14:44:45] [main/WARN]: Error loading class: net/minecraft/client/MinecraftClient (java.lang.ClassNotFoundException: net/minecraft/client/MinecraftClient)
[14:44:45] [main/WARN]: @Mixin target net.minecraft.client.MinecraftClient was not found spiffyhud.mixin.json:MixinMinecraft
[14:44:45] [main/WARN]: Error loading class: net/minecraft/client/gui/hud/InGameHud (java.lang.ClassNotFoundException: net/minecraft/client/gui/hud/InGameHud)
[14:44:45] [main/WARN]: @Mixin target net.minecraft.client.gui.hud.InGameHud was not found spiffyhud.mixin.json:MixinInGameHud
[14:44:45] [main/WARN]: Error loading class: net/minecraft/scoreboard/Scoreboard (java.lang.ClassNotFoundException: net/minecraft/scoreboard/Scoreboard)
[14:44:45] [main/WARN]: @Mixin target net.minecraft.scoreboard.Scoreboard was not found spiffyhud.mixin.json:MixinScoreboard
[14:44:45] [main/WARN]: Error loading class: net/minecraft/client/gui/hud/InGameHud (java.lang.ClassNotFoundException: net/minecraft/client/gui/hud/InGameHud)
[14:44:45] [main/WARN]: @Mixin target net.minecraft.client.gui.hud.InGameHud was not found spiffyhud.mixin.json:IMixinInGameHud
[14:44:45] [main/WARN]: Error loading class: net/minecraft/item/ItemStack (java.lang.ClassNotFoundException: net/minecraft/item/ItemStack)
[14:44:45] [main/WARN]: @Mixin target net.minecraft.item.ItemStack was not found spiffyhud.mixin.json:MixinItemStack
[14:44:45] [main/WARN]: Error loading class: net/minecraft/client/Mouse (java.lang.ClassNotFoundException: net/minecraft/client/Mouse)
[14:44:45] [main/WARN]: @Mixin target net.minecraft.client.Mouse was not found spiffyhud.mixin.json:MixinMouse
[14:44:45] [main/WARN]: Error loading class: net/minecraft/client/network/ClientPlayerInteractionManager (java.lang.ClassNotFoundException: net/minecraft/client/network/ClientPlayerInteractionManager)
[14:44:45] [main/WARN]: @Mixin target net.minecraft.client.network.ClientPlayerInteractionManager was not found spiffyhud.mixin.json:MixinClientPlayerInteractionManager
[14:44:45] [main/WARN]: Error loading class: net/minecraft/client/gui/hud/DebugHud (java.lang.ClassNotFoundException: net/minecraft/client/gui/hud/DebugHud)
[14:44:45] [main/WARN]: @Mixin target net.minecraft.client.gui.hud.DebugHud was not found spiffyhud.mixin.json:MixinDebugHud
[14:44:48] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zdg000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.

-----

[14:44:56] [Render thread/WARN]: Error loading class: net/minecraft/server/world/ServerWorld (java.lang.ClassNotFoundException: net/minecraft/server/world/ServerWorld)
[14:44:56] [Render thread/WARN]: Error loading class: net/minecraft/server/world/ServerWorld (java.lang.ClassNotFoundException: net/minecraft/server/world/ServerWorld)
[14:44:56] [Render thread/WARN]: Error loading class: net/minecraft/server/world/ServerWorld (java.lang.ClassNotFoundException: net/minecraft/server/world/ServerWorld)
[14:44:56] [Render thread/WARN]: Error loading class: net/minecraft/server/world/ServerWorld (java.lang.ClassNotFoundException: net/minecraft/server/world/ServerWorld)
[14:44:56] [Render thread/WARN]: Error loading class: net/minecraft/server/world/ServerWorld (java.lang.ClassNotFoundException: net/minecraft/server/world/ServerWorld)
[14:44:56] [Render thread/INFO]: [KONKRETE] Successfully initialized!
[14:44:56] [Render thread/INFO]: [KONKRETE] Server-side libs ready to use!
[14:44:57] [Render thread/INFO]: Failed to find module info for C:\Users\KNote\OneDrive\Documents\MultiMC\instances\Test\natives\lwjgl.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:207) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[14:44:57] [Render thread/INFO]: Failed to find module info for C:\Users\KNote\OneDrive\Documents\MultiMC\instances\Test\natives\jemalloc.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:207) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by Keksuccino** [comment]
SpiffyHUD got a full rewrite now, so I will close this issue for now.
If you still have problems, please open a new one, thank you very much!
